FROM mcr.microsoft.com/dotnet/sdk:8.0

# Install essential tools
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
        git \
        curl \
        unzip \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

# Install SQL Server tools
RUN curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc \
    && curl https://packages.microsoft.com/config/debian/11/prod.list | tee /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev \
    && echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc

WORKDIR /app
#install azure client
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash
#use git in containers
RUN git config --global user.email "collinsentrepreneur@gmail.com"
RUN git config --global user.name "CollinsMunene-Developer"
#configure the port for the app 
EXPOSE 4000